<a href="https://colab.research.google.com/github/saii4u/Data-science/blob/main/Phython_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
print("hello world")

hello world


In [61]:
x = 2 
print(x)

2


In [38]:
import math

In [41]:
math.sqrt(256)

16.0

In [44]:
math.sqrt(1024)

32.0

In [45]:
math.sqrt(500)

22.360679774997898

In [46]:
round(125.89575,3)

125.896

In [47]:
3 > 10

False

In [48]:
5255 < 245875

True

In [49]:
5+75

80

In [50]:
85-3

82

In [51]:
7*7

49

In [52]:
8 * 8

64

In [54]:
10 == 10

True

In [55]:
15 == 10

False

In [56]:
5 <= 5

True

In [57]:
5 <= 10

True

In [58]:
10 >= 10

True

In [103]:
(5 > 10) | (100 > 45)

True

In [102]:
(25 ==
25) & (45 < 100)

True

In [69]:
not (10 > 10)

True

Loops
while
or 
if

In [101]:
from re import I
i = 0
while i <=5:
  print(i)
  i = i+1

0
1
2
3
4
5


In [100]:
i = 20
while i <=10:
  print(i)
  i = i+1
print("Loop Ends")


Loop Ends


Range function
[] used for lists.

In [99]:
list(range(4))

[0, 1, 2, 3]

In [98]:
range (5)

range(0, 5)

In [97]:
for i in range(5):
  print("sai")

sai
sai
sai
sai
sai


In [92]:
import numpy as np
from numpy.random import randn

In [95]:
x = randn()
if x>1:
  result = "greater than 1"
print(x)
print(result)

2.5236967382199107
greater than 1


In [96]:
result = None
x = randn()
if x>1:
  result = "greater than 1"
print(x)
print(result)

-2.0514947391735787
None


In [93]:
result = None
x = randn()
if x>1:
  result = "greater than 1"
if x<1:
  result = "less than 1"
print(x)
print(result)

0.17422654369007787
less than 1


In [94]:
result = None
x = randn()
if x>1:
  result = "greater than 1"
elif x<1:
  result = "less than 1"
else:
  result = "between -1 and 1"
print(x)
print(result)

-2.4909864766536067
less than 1


In [135]:
result = None
x = int(input())
if x>1:
  result = "greater than 1"
elif x<1:
  result = "less than 1"
else:
  result = "between -1 and 1"
print(x)
print(result)

-5
-5
less than 1



Creating a List

In [11]:
list1 = [1,2,2,2,'abc','good job', True, 20]

In [4]:
type(list1)

list

Indexing in phython always starts from '0'

In [6]:
list1[5]

'good job'

In [13]:
list1[2] = 'Pirate King'

In [14]:
list1[2]

'Pirate King'

Getting Data from list or slicing

In [15]:
list1[2:5]

['Pirate King', 2, 'abc']

In [17]:
list1[::2]

[1, 'Pirate King', 'abc', True]

In [18]:
list1[::-1]

[20, True, 'good job', 'abc', 2, 'Pirate King', 2, 1]

Tuple:
Tuple is an immutable sequence of values.
That is once a list is defined it cannot be changed.
If an element is to be changed it throws an error. 
Tuples are defined using () and not []
Tuple are used when we want a fixed list.

In [22]:
tuple1= (1,9, 'sai', 'ram', 7.7, 'abc')

In [24]:
type(tuple1)

tuple

In [29]:
tuple1[2:4]

('sai', 'ram')

In [44]:
range(101,113)

range(101, 113)

In [45]:
list(range(101,113))

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]

In [46]:
mylist1 = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]

In [47]:
print(mylist1)

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112]


In [48]:
len([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

12

In [49]:
type(12)

int

In [50]:
max(mylist1)

112

In [51]:
min(mylist1)

101

In [52]:
max("processwhirl")

'w'

In [53]:
min("processwhirl")

'c'

Package and Module in Phython

In [54]:
import scrapy
from scrapy.crawler import crawlerprocess

ModuleNotFoundError: ignored

Arrays :Array are bulit in core phython. Array should have only one kind of data. suppose if has both numeric and string then everything turns into string.

In [56]:
import numpy as np

In [57]:
from ctypes import Array
a = np.array(list1)
print(a)

['1' '2' 'Pirate King' '2' 'abc' 'good job' 'True' '20']


In [58]:
a

array(['1', '2', 'Pirate King', '2', 'abc', 'good job', 'True', '20'],
      dtype='<U21')

In [69]:
b = np.array([5,10,45,20])

In [70]:
b.mean()

20.0

In [73]:
b

array([ 5, 10, 45, 20])

In [72]:
b[::2]

array([ 5, 45])

In [74]:
b[1::2]

array([10, 20])

In [75]:
c = b[2::4]

In [76]:
c

array([45])

In [78]:
c[:] = 111

In [79]:
c

array([111])

In [80]:
b

array([  5,  10, 111,  20])

In [83]:
print(b)

[  5  10 111  20]
